### ISSUE TITLE
Building 2.0.0

### ISSUE THREAD

**Issue by Ryushin** [quantum/esos#229] opened 2019-03-13 22:15 UTC
This is a continuation from https://groups.google.com/forum/#!topic/esos-users/WCoxa8XwPrM as messages were being deleted there.

Trying to compile 2.0.0 on Devuan Ceres (systemd-less Debian Sid).  Never did get that to work. 

Set up a Ubuntu 12.04 build host but it would error out on the make build options.  Ubuntu 14.04 did the same.  Only once I upgraded to 16.04 would it build correctly.  Please update the instructions to use 16.04 as a build host:
https://github.com/quantum/esos/wiki/11_Building#building-esos

I'm currently testing 2.0.0 under Libvirt/KVM virtual machine and it seems to be missing the virtio drivers.  I was reading that ZFSonLinux was included but that does not seem to be the case.  Is there a build option that I'm missing.  I'm planning on running zvols for the fibre channel targets.

**Comment by msmith626** [comment] 2019-03-14 12:50
Hi,

Sorry for the trouble on the esos-users Google Group... your messages were being marked as spam, but there is a significant delay between when you post and I'm notified of the suspended messages.

Thank you for the Ubuntu build host information; we need to update that whole section, as I don't believe all of those packages are needed for each platform in order build, and we should update the build example distros to the latest versions.

Which Virtio drivers are missing? I use ESOS in QEMU/KVM without issue, but perhaps we're missing a specific driver? For ZFS, you need to build with the "--enable-zfs" autoconf option (when running ./configure).

--Marc

**Comment by Ryushin** [comment] 2019-03-14 18:48
The libvirt scsi module seems to be missing.

At least you have it working fine under a QEMU/KVM.  I'm stilling having issues with Windows Initiators not working with SCST.  Windows Initiators (2008 R2 and 2012 R2) both throw "Parameter is incorrect" when doing anything with the drive in the Drive Manager or Diskpart.

I was hoping ESOS would work correctly.  Seems to have the same issues as the SCST source.  
See: https://sourceforge.net/p/scst/mailman/message/36610140/

Your tool seems must easier to make changes quickly.  Working on changing the sector size even though parted shows 512 for everything.

**Comment by msmith626** [comment] 2019-03-14 18:55
It's not a module in ESOS (as most drivers aren't):
# zcat /proc/config.gz | grep -i scsi_virtio
CONFIG_SCSI_VIRTIO=y

Anything useful in Windows event viewer? It might give you more detail when you get that generic initialization error.

--Marc

**Comment by Ryushin** [comment] 2019-03-14 19:12
Windows System log shows nothing of course.  Shame.  I wonder if there is some kind of debugging option in the QLogic QLE2562 driver.  I'll check for that now.

**Comment by msmith626** [comment] 2019-03-14 19:36
You're using ZFS volumes, correct? What volume block size did you
choose? Can you provide the contents of the
/sys/block/zdN/queue/physical_block_size and
/sys/block/zdN/queue/logical_block_size attributes for your ZFS volume
block devices?

--Marc

**Comment by Ryushin** [comment] 2019-03-14 19:48
I'm currently testing with one very large 115TB zvol and 20GB qcow2 file.  Both shows the same problems.  The zvol is set up as a raw disk in the QEMU/KVM.
I am using 512 block size but I've been testing other sizes in case that was the problem.

The host, that has the 115TB zvol shows: 
physical_block_size=8192
logical_block_size=512

The QEMU/KVM
The 20GB qcow2 shows:
physical_block_size=512  logical_block_size=512

The 115TB zvol shows:
physical_block_size=512  logical_block_size=512

I'm mostly just doing testing against the 20GB qcow2 file in order to tray and get this to work.

Linux Initiators have no problems connecting and manipulating LUNs.  Everything is running through QLogic SanBox 8GB switches.

Thank you for your time and help.  I've been working on this issue since December.  Problem occurs with TargetCLI as well.  Same symptoms.

**Comment by msmith626** [comment] 2019-03-15 02:37
Might be interesting to try and eliminate the ZFS volume from the equation,
just to see if you get any different behavior. In ESOS, if you have a real
backing device (eg, SCSI disk, etc.) create a vdisk_blockio SCST device on
it and map it. Or create a file system in ESOS (eg, XFS) then create a
"virtual disk file" on that FS in ESOS, and create the SCST device using
vdisk_fileio.

--Marc

**Comment by Ryushin** [comment] 2019-03-15 13:14
Finally tracked down the problem.  The Windows servers that are running the initiators are running TigerSAN software which prevents manipulating the LUNs.  Putting the TigerSAN software in maintenance mode allows everything to work properly.  Only once we opened a Ticket with Tiger in the hope of them coming across this problem, did they say it was be design.

Thank you so much for you help.  I'm glad this is finally sorted it.

**Comment by msmith626** [comment] 2019-03-15 16:50
Ha, that's too funny. I actually thought TigerStore might be the cause
myself: I had another user that described very similar symptoms
sometime back, and it ended up being his TigerStore software which
claims/locks the volumes, and doesn't allow access (exactly what you
described). Last night as I was writing you back, I even searched my
email looking for that error message you provided, but it didn't
match, so I assumed it was something different!

Glad you figured it out, thanks for the update.

--Marc

**Closed** 2019-03-22 14:13 UTC
Labels: question
